# App
spring.application.name=wellcheck

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wellcheck_db
spring.datasource.username=postgres
spring.datasource.password=2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Port
server.port=8080